vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        thumbnails:
            uri_prefix: /images/thumbnails
            upload_destination: '%kernel.project_dir%/public/images/thumbnails'


        attachments:
            uri_prefix: /images/attachments
            upload_destination: '%kernel.project_dir%/public/images/attachments'
